### ISSUE TITLE
USER STORY: Matching label size with paper size

### ISSUE THREAD

**Issue by KristianDsmith** [KristianDsmith/my-first-agile-project1-2023#2]
As a **warehouse operator** I can **select papper size on which to print** so that **the printed label size matches the parcel size**

**Comment by KristianDsmith** [comment]
#accecptance criteria 

* 1. Order details include the order id, the shipping address, and the list of items in the parcel
* 2. The warehouse employee can select the size of the order details from 3 sizes (A4,A5, and A6)
* 3. Font size used is 12 points
*

**Comment by KristianDsmith** [comment]
#Tasks
- [ ] Design a "print" icon and add it to the order details page
- [ ] Design the print layouts for different page sizes
- [ ] Create the HTML and CSS for the dropdown menu including the paper size
- [ ] Create the code for the model, viewer, and controller
- [ ] test the completed functionality

**Comment by KristianDsmith** [comment]
This is completed
