### ISSUE TITLE
USER STORY: <1>

### ISSUE THREAD

**Issue by KristianDsmith** [KristianDsmith/my-first-agile-project1-2023#3]
In order to **provide my opinion with regards to a certain running topic or event** as a **user**, I can **select and submit an answer from the poll**

**Comment by KristianDsmith** [comment]
##Acceptance Criteria:

*a. The option should be provided as a checkbox
*b. The checkbox should be “checked” by default
*c. The option should appear next to the submit button
*d. After submitting the default submission confirmation should be adjusted to include the user name.

**Comment by KristianDsmith** [comment]
#Tasks
- [ ] Update the view: the poll design (HTML and CSS) to include the checkbox and to show the name of the submitter
- [ ] Create a new field in the model to track the username
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test the functionality
