### ISSUE TITLE
USER STORY: 2

### ISSUE THREAD

**Issue by KristianDsmith** [KristianDsmith/my-first-agile-project1-2023#7]
In order to **automatically hide the poll** as an **administrator**, I can **pick the expiry date while publishing the poll**

**Comment by KristianDsmith** [comment]
#Acceptamce Criteria:
* a. The poll should disappear at 11:59 PM onnthe target date
* b. The real estate of the "Poll" should be reserved on the home page. a message that says "Stay Tuned, a new poll is coming soon" should appear if no other Poll is active.
* c. The administrator expiry date should be at least 3 days after the current date.

**Comment by KristianDsmith** [comment]
#Tasks
- [ ] Update the admin module view: the poll design (HTML and CSS) to include a date picker
- [ ] Update the website view: show "Stay tuned, a new poll is coming soon"
- [ ] Create a JavaScript function to validate that the expiry date is at least after 3 days.
- [ ] Create a job to check expired Polls every day at 11:59 PM and Hide them
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test the functionality
